@ECommerce_API_HostAddress = https://localhost:7102
@Token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwMWEwZTIxYy1hNzI0LTc4NTItYWNkZS0zNmZkYjE1Njk4OTMiLCJlbWFpbCI6ImFkbWluQHRlc3QuY29tIiwianRpIjoiYjNmNmMwYmEtNzA4NS00MGNjLWI4MzgtNDBkZDE1NjRkZjBhIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQWRtaW4iLCJuYmYiOjE3OTA1MTc4NTQsImV4cCI6MTc5MDUyMTQ1NCwiaXNzIjoiRUNvbW1lcmNlLkFQSSIsImF1ZCI6IkVDb21tZXJjZS5BUEkifQ.NoD1dtqYWq8Bys--uDfCPaouNqlm_gcmCvItf5Yg_HU

GET {{ECommerce_API_HostAddress}}/api/products/cafb0c28-52bf-4d4c-817f-9dd42ad9ee3c
Accept: application/json

###
POST {{ECommerce_API_HostAddress}}/api/products
Content-Type: application/json

{
  "name": "Samsung S26 Ultra",
  "description": "Samsung smartphone",
  "brandId": "08d66b91-da02-474e-b873-3f9dd1656b20",
  "categoryId": "822a39ea-a5d2-47bb-bbbc-67f4165177eb"
}
###
POST {{ECommerce_API_HostAddress}}/api/products
Content-Type: application/json

{
  "name": "",
  "description": "",
  "brandId": "00000000-0000-0000-0000-000000000000",
  "categoryId": "00000000-0000-0000-0000-000000000000"
}
###
GET {{ECommerce_API_HostAddress}}/api/brands/08d66b91-da02-474e-b873-3f9dd1656b20
Accept: application/json

###
POST {{ECommerce_API_HostAddress}}/api/brands
Content-Type: application/json

{
  "name": "Samsung"
}
###
POST {{ECommerce_API_HostAddress}}/api/categories
Content-Type: application/json

{
  "name": "TV",
  "parentCategoryId": "59fa1994-6a2a-4647-a6c9-c08dc8142fad"
}
###
GET {{ECommerce_API_HostAddress}}/api/categories/822a39ea-a5d2-47bb-bbbc-67f4165177eb
Accept: application/json

###
POST {{ECommerce_API_HostAddress}}/api/product-variants
Content-Type: application/json

{
  "productId": "4b67459d-e12a-4c5b-b244-437d89756661",
  "sku": "IPHONE-17-128-BLK",
  "name": "Black 128GB"
}
###
GET {{ECommerce_API_HostAddress}}/api/product-variants/72e245c7-7e84-42d5-8844-ef766bd3f052
Accept: application/json

###
POST {{ECommerce_API_HostAddress}}/api/product-images
Content-Type: application/json

{
  "productId": "4b67459d-e12a-4c5b-b244-437d89756661",
  "productVariantId": "72e245c7-7e84-42d5-8844-ef766bd3f052",
  "url": "https://example.com/iphone-front.jpg",
  "altText": "iphone front view",
  "sortOrder": 2,
  "isPrimary": false
}
###
GET {{ECommerce_API_HostAddress}}/api/product-images/535f2f92-e5c6-401b-9ecb-2313cac9ec3d
Accept: application/json

###
POST {{ECommerce_API_HostAddress}}/api/seller-offers
Content-Type: application/json
Authorization: Bearer {{Token}}

{
  "productVariantId": "72e245c7-7e84-42d5-8844-ef766bd3f052",
  "price": 50000000,
  "stock": 10
}
###
GET {{ECommerce_API_HostAddress}}/api/seller-offers/9c0db6d2-fd7c-4039-9032-692fac6de236
Accept: application/json

###
POST {{ECommerce_API_HostAddress}}/api/seller-requests
Content-Type: application/json
Authorization: Bearer {{Token}}

{
  "reason": "I want to sell TVs and Mobile phones."
}
###
GET {{ECommerce_API_HostAddress}}/api/seller-requests/e4552ccc-b6e9-427b-ba5d-2f8845771579
Accept: application/json

###
POST {{ECommerce_API_HostAddress}}/api/seller-requests/47501b40-65fb-4cbf-b121-5f1ffe1b4043/approve
Content-Type: application/json
Authorization: Bearer {{Token}}

###
POST {{ECommerce_API_HostAddress}}/api/seller-requests/e4552ccc-b6e9-427b-ba5d-2f8845771579/reject
Content-Type: application/json
Authorization: Bearer {{Token}}

###
PUT {{ECommerce_API_HostAddress}}/api/seller-offers/price
Content-Type: application/json
Authorization: Bearer {{Token}}

{
  "price": 160000,
  "rowVersion": 932
}
###
PUT {{ECommerce_API_HostAddress}}/api/seller-offers/stock
Content-Type: application/json
Authorization: Bearer {{Token}}

{
  "sellerOfferId": "9c0db6d2-fd7c-4039-9032-692fac6de236",
  "stock": 20,
  "rowVersion": 934
}
###
PUT {{ECommerce_API_HostAddress}}/api/seller-offers/activate
Content-Type: application/json
Authorization: Bearer {{Token}}

{
  "sellerOfferId": "9c0db6d2-fd7c-4039-9032-692fac6de236",
  "rowVersion": 938
}
###
PUT {{ECommerce_API_HostAddress}}/api/seller-offers/deactivate
Content-Type: application/json
Authorization: Bearer {{Token}}

{
  "sellerOfferId": "9c0db6d2-fd7c-4039-9032-692fac6de236",
  "rowVersion": 936
}
###
POST {{ECommerce_API_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "email": "seller@test.com",
  "password": "Password123!"
}
###